spring:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    users:
      path: /myService/**
      serviceId: cloud-provider
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000